### ISSUE TITLE
Scopes are not chainable

### ISSUE THREAD

**Issue by andreynering** [active-hash/active_hash#247]
Hey there!

Thanks for this project! We use it extensively at JobScore and love it.

I'd like to request something, though. Scopes work in isolation, but you can't use more than one together, which works in ActiveRecord and is extremely convenient. Could this possibly be implemented?

```ruby
class Vehicle
  scope :car, -> { where(type: 'car' }
  scope :motorized, -> { where(motorized: true}
end
```

```ruby
> Vehicle.car.motorized
NoMethodError: undefined method `motorized' for #<ActiveHash::Relation:0x000000010732d9c8>
```

**Comment by andreynering** [comment]
I just gave it a try at https://github.com/active-hash/active_hash/pull/248
