### ISSUE TITLE
Release master for Ruby 3 compatibility

### ISSUE THREAD

**Issue by nsommer** [active-hash/active_hash#225]
Would you consider bumping the version and doing a release of master? ActiveHash currently does not run with Ruby 3, but it was already fixed on master (https://github.com/zilkey/active_hash/commit/f6448312c748f7e0f2846ed0d377074c974d3f7d).

**Comment by nsommer** [comment]
@kbrock @syguer any chance you would release soonish? 🙂

**Comment by kbrock** [comment]
Hi @syguer -- are you the one to push these changes live?
Anything other people need to do to help with this effort?

**Comment by aknicol** [comment]
Have these issues for Ruby 3 been resolved? I'm still receiving `Undefined method 'arity'` on my model definitions.

**Comment by aknicol** [comment]
As I mentioned I'm still having issues, my code follows the example in the docs almost exactly, I have: 

```
class Person < ActiveRecord::Base

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :country

```
 
on the next line, 

`  belongs_to :surname, optional: true
`
I get the error **undefined method `arity' for {:optional=>true}:Hash**

**Comment by cath-oneill** [comment]
Finally upgrading to Ruby 3, and running into the same issues.  It does appeared to be fixed for my use-case both in master ([f644831](https://github.com/zilkey/active_hash/commit/f6448312c748f7e0f2846ed0d377074c974d3f7d)) as @nsommer pointed out, and @gazayas' offered another possible fix in his PR.  Anything that can be done to help get the work that's already been done released?

**Comment by Sixeight** [comment]
@zilkey Could you release a new version? Current version has some problem with Ruby 3.x.
Or, How about an idea create new organization for this library to maintain the software by community.
Thanks for the great library!

**Comment by Sixeight** [comment]
https://github.com/active-hash had been created. but the new version has not been released. does anyone has manageable permission?

**Comment by aknicol** [comment]
Has there been any progress on this?

**Comment by yujideveloper** [comment]
v3.1.1 has been released that supports Ruby 3.x.
https://rubygems.org/gems/active_hash/versions/3.1.1

**Comment by neocoin** [comment]
Please release version v3.1.2.  

I've made some monkey patches to make active_hash work in Ruby 3.2 and Rails 7. 

For example, I must need these commits.

00f98114f9b3c22010a47f3f7b35b7aed1a33b5d
bb111597fc2214f02670fb5d2d35f374a5f98466

**Comment by yujideveloper** [comment]
@neocoin 
Sorry, I don't have commit and release permissions.

@adampal @kbrock 
Could you release a new version?

**Comment by kbrock** [comment]
I just checked, I'm not an owner in gems. That is all @adampal or @flavorjones (the ones that I think are active).
Also, could we merge #268 first? it has generated so many PRs and issues. Just in final review status.

**Comment by flavorjones** [comment]
@kbrock I'll make you an owner in rubygems -- can you confirm your username or email address for me?

**Comment by flavorjones** [comment]
@kbrock You've been invited as an owner on rubygems.org! :tada:

**Comment by franzliedke** [comment]
v3.2.0 is out. Thanks, @kbrock! 🎉 

(So this can probably be closed now.)
